### PR TITLE
Fix .cfg validation on Launch

### PR DESCRIPTION
**Pull request by mattie078**
The new launcher is pretty nice with all the features it has but one thing bugs me the most:

Every time you launch the game. EVERY file gets checked on the hash value for potential corruption. 
Any chances to .cfg files will change the hash, so it replaces the file with a brand new one. Deleting any changes to it.

This is also why waypoints from Journeymap gets deleted, but I don't have time untill Friday to check that out.

### CODE REVIEW

**Comment by Brend-Smits** [comment]
Thanks a lot for the PR Mattie, I just fixed the Journeymap issue. 
However, I think this PR might still be useful due to the launcher still checking other configs every time on launch. 

Tomorrow I will have time to dive into this and to look into this pull request more.

**Comment by Brend-Smits** [comment]
I also just updated the base branch from master to develop, please update the target branch :) Thanks again!

**Comment by Brend-Smits** [comment]
I've thought about this some more and I'm trying to look at a broader picture... I think it might be best to make a folder of sorts that is 'untracked' and does not have an MD5 tag(so are not checked every time)... However, this approach takes more time for sure.

I think this solution is fine for now and serves more like a temporary workaround until we can implement the above solution. I will be testing the solution thoroughly in a little bit and provide feedback.

**Comment by mattie078** [comment]
Yeah so I was thinking of implementing some sort of config file, like .gitignore for the files that won't be checked. I think that's also what you seems to have in mind? 

In addition to this, maybe an extra button in the settings of the app to still force validate everything but only on request?

**Comment by Brend-Smits** [comment]
> Yeah so I was thinking of implementing some sort of config file, like .gitignore for the files that won't be checked. I think that's also what you seems to have in mind?
> 
> In addition to this, maybe an extra button in the settings of the app to still force validate everything but only on request?

Yeah, that's exactly like I had in mind, except that the '.gitignore' will also need to be able to block full-on file extensions like '.cfg', or folder. Otherwise, it would be difficult to set a modpack up that has over 200 mods.
I think this would be difficult to set up though, not too experienced with Electron/Javascript yet.

**Comment by mattie078** [comment]
Yes exactly. I'm also not sure of that would be easy to implement but it would add a pretty easy way to configure file validation. 

I also don't have much experience with Electron, So this will also require a bit of trial and error to figure out. I will probably try some things out later tomorrow.

**Comment by Brend-Smits** [comment]
Good news, it seems like upstream has a new update that includes the exact change that we discussed above with a git ignore style file! I will look into updating our launcher asap to include and test this change :) Once I've done that I will update this PR and close it.

**Comment by Brend-Smits** [comment]
This is now implemented, open an issue if there are issues!

**Pull request closed without merging**
